version: 0.2
phases:
    install:
        commands:
            - ./build
            - npm-recursive-install --production
    build:
        commands:
            - stackbuilder-py build || exit 1
            - aws cloudformation package  --template-file template.yaml --output-template-file packaged-template.json --s3-bucket yieldai-stack-build --use-json || exit 1
artifacts:
    files:
        - packaged-template.json
        - template-config-dev.json
        - template-config-prod.json
