GenericTable:
    Type: AWS::DynamoDB::Table
    Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
        AttributeDefinitions:
            - AttributeName: pk
              AttributeType: S
            - AttributeName: sk
              AttributeType: S
        PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: true
        StreamSpecification:
            StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
            - IndexName: reverse-lookup
              KeySchema:
                  - AttributeName: sk
                    KeyType: HASH
                  - AttributeName: pk
                    KeyType: RANGE
              Projection:
                  ProjectionType: ALL
