AuroraDBClusterSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
        DBSubnetGroupDescription: Subnets for db
        SubnetIds:
            - !Ref Subnet1
            - !Ref Subnet2
            - !Ref Subnet3
