AuroraDBClusterSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties: 
    VpcId: !Ref VPC
    GroupDescription: LambdaSecurityGroup
    SecurityGroupIngress:
      - CidrIp: '10.100.0.0/16'
        FromPort: 3306
        IpProtocol: tcp
        ToPort: 3306
      - CidrIp: 172.31.0.0/16
        FromPort: 3306
        IpProtocol: tcp
        ToPort: 3306
      - CidrIp: 0.0.0.0/0
        FromPort: 3306
        IpProtocol: tcp
        ToPort: 3306