PrivateRouteTable:
  Type: AWS::EC2::RouteTable
  Properties: 
    VpcId: !Ref VPC
    
PublicRouteTable:
  Type: AWS::EC2::RouteTable
  Properties: 
    VpcId: !Ref VPC
    
PublicGatewayRoute:
  Type: AWS::EC2::Route
  Properties:
    RouteTableId: !Ref PublicRouteTable
    GatewayId: !Ref InternetGateway
    DestinationCidrBlock: '0.0.0.0/0'