DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        ContentUri: ./Layers/DependencyLayer
        RetentionPolicy: Delete
        CompatibleRuntimes:
            - nodejs18.x
